version: '3.8'

services:
  # Dịch vụ Cơ sở dữ liệu (Database Service)
  db:
    image: ankane/pgvector
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-cv_evaluator_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Dịch vụ Backend (FastAPI App)
  web:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      # Chuẩn hóa Hostname về tên service "db"
      - POSTGRES_SERVER=db
      - DATABASE_URL=postgresql+psycopg2://postgres:123456@db:5432/cv_evaluator_db
    depends_on:
      - db

volumes:
  postgres_data:
