"""update job-cv relationship

Revision ID: 282bfb1bbd2c
Revises: 228f0c8e1a9f
Create Date: 2026-03-19 21:25:37.726027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '282bfb1bbd2c'
down_revision: Union[str, Sequence[str], None] = '228f0c8e1a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CVs', sa.Column('PositionId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'CVs', 'Jobs', ['PositionId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CVs', type_='foreignkey')
    op.drop_column('CVs', 'PositionId')
    # ### end Alembic commands ###
