"""update job-cv to position relationship

Revision ID: 43dda7c82982
Revises: 282bfb1bbd2c
Create Date: 2026-03-19 21:26:39.499611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '43dda7c82982'
down_revision: Union[str, Sequence[str], None] = '282bfb1bbd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
