"""init tables

Revision ID: 6d45b69f2a75
Revises: 
Create Date: 2026-02-01 00:34:11.117106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '6d45b69f2a75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Candidates',
    sa.Column('FullName', sa.String(length=200), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=50), nullable=True),
    sa.Column('Location', sa.String(length=200), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Candidates_Email'), 'Candidates', ['Email'], unique=True)
    op.create_index(op.f('ix_Candidates_FullName'), 'Candidates', ['FullName'], unique=False)
    op.create_table('Hr',
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('FullName', sa.String(length=200), nullable=True),
    sa.Column('Status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', name='userstatus'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email', name='uq_hr_email')
    )
    op.create_index(op.f('ix_Hr_Email'), 'Hr', ['Email'], unique=True)
    op.create_table('Jobs',
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('RequirementsText', sa.Text(), nullable=True),
    sa.Column('MinExperience', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('EducationLevel', sa.Enum('HIGH_SCHOOL', 'BACHELOR', 'MASTER', 'PHD', name='educationlevel'), nullable=True),
    sa.Column('Status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'DELETED', name='jobstatus'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Skills',
    sa.Column('Name', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('Category', sa.String(length=100), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Skills_Category'), 'Skills', ['Category'], unique=False)
    op.create_index(op.f('ix_Skills_Name'), 'Skills', ['Name'], unique=True)
    op.create_table('CVs',
    sa.Column('CandidateId', sa.Integer(), nullable=False),
    sa.Column('FileUrl', sa.String(length=500), nullable=False),
    sa.Column('FileType', sa.Enum('PDF', 'DOCX', 'TXT', name='cvfiletype'), nullable=True),
    sa.Column('RawText', sa.Text(), nullable=True),
    sa.Column('CleanText', sa.Text(), nullable=True),
    sa.Column('Summary', sa.Text(), nullable=True),
    sa.Column('Language', sa.String(length=20), server_default='en', nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['CandidateId'], ['Candidates.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('JobEmbeddings',
    sa.Column('JobId', sa.Integer(), nullable=False),
    sa.Column('ModelName', sa.String(length=100), nullable=False),
    sa.Column('Vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('EmbeddingType', sa.Enum('ALL', name='embeddingtype'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['JobId'], ['Jobs.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('JobSkills',
    sa.Column('JobId', sa.Integer(), nullable=False),
    sa.Column('SkillId', sa.Integer(), nullable=False),
    sa.Column('Importance', sa.Numeric(precision=5, scale=2), server_default='1.0', nullable=True),
    sa.Column('MinYears', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['JobId'], ['Jobs.Id'], ),
    sa.ForeignKeyConstraint(['SkillId'], ['Skills.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('JobId', 'SkillId', name='uq_job_skill')
    )
    op.create_table('ScreeningBatches',
    sa.Column('JobId', sa.Integer(), nullable=False),
    sa.Column('TriggeredBy', sa.Integer(), nullable=False),
    sa.Column('TotalCV', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ProcessedCV', sa.Integer(), server_default='0', nullable=False),
    sa.Column('Status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='batchstatus'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['JobId'], ['Jobs.Id'], ),
    sa.ForeignKeyConstraint(['TriggeredBy'], ['Hr.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('CVEmbeddings',
    sa.Column('CVId', sa.Integer(), nullable=False),
    sa.Column('ModelName', sa.String(length=100), nullable=False),
    sa.Column('Vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('EmbeddingType', sa.Enum('ALL', name='embeddingtype'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['CVId'], ['CVs.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('CVSkills',
    sa.Column('CVId', sa.Integer(), nullable=False),
    sa.Column('SkillId', sa.Integer(), nullable=False),
    sa.Column('Confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Source', sa.String(length=100), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['CVId'], ['CVs.Id'], ),
    sa.ForeignKeyConstraint(['SkillId'], ['Skills.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('CVId', 'SkillId', name='uq_cv_skill')
    )
    op.create_table('Educations',
    sa.Column('CVId', sa.Integer(), nullable=False),
    sa.Column('Degree', sa.String(length=200), nullable=True),
    sa.Column('Major', sa.String(length=200), nullable=True),
    sa.Column('School', sa.String(length=200), nullable=True),
    sa.Column('Level', sa.Enum('HIGH_SCHOOL', 'BACHELOR', 'MASTER', 'PHD', name='educationlevel'), nullable=True),
    sa.Column('GraduationYear', sa.Integer(), nullable=True),
    sa.Column('GPA', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['CVId'], ['CVs.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Experiences',
    sa.Column('CVId', sa.Integer(), nullable=False),
    sa.Column('Company', sa.String(length=200), nullable=False),
    sa.Column('Position', sa.String(length=200), nullable=True),
    sa.Column('StartDate', sa.Date(), nullable=True),
    sa.Column('EndDate', sa.Date(), nullable=True),
    sa.Column('DurationMonths', sa.Integer(), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['CVId'], ['CVs.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('MatchResults',
    sa.Column('CVId', sa.Integer(), nullable=False),
    sa.Column('JobId', sa.Integer(), nullable=False),
    sa.Column('SemanticScore', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('SkillScore', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ExperienceScore', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('EducationScore', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('TotalScore', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('Rank', sa.Integer(), nullable=True),
    sa.Column('EvaluatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['CVId'], ['CVs.Id'], ),
    sa.ForeignKeyConstraint(['JobId'], ['Jobs.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('CVId', 'JobId', name='uq_cv_job_match')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MatchResults')
    op.drop_table('Experiences')
    op.drop_table('Educations')
    op.drop_table('CVSkills')
    op.drop_table('CVEmbeddings')
    op.drop_table('ScreeningBatches')
    op.drop_table('JobSkills')
    op.drop_table('JobEmbeddings')
    op.drop_table('CVs')
    op.drop_index(op.f('ix_Skills_Name'), table_name='Skills')
    op.drop_index(op.f('ix_Skills_Category'), table_name='Skills')
    op.drop_table('Skills')
    op.drop_table('Jobs')
    op.drop_index(op.f('ix_Hr_Email'), table_name='Hr')
    op.drop_table('Hr')
    op.drop_index(op.f('ix_Candidates_FullName'), table_name='Candidates')
    op.drop_index(op.f('ix_Candidates_Email'), table_name='Candidates')
    op.drop_table('Candidates')
    # ### end Alembic commands ###
