"""remove embeddingtype

Revision ID: 71079262d6bc
Revises: ef942e427254
Create Date: 2026-03-23 21:31:58.829109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '71079262d6bc'
down_revision: Union[str, Sequence[str], None] = 'ef942e427254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CVEmbeddings', 'EmbeddingType')
    op.drop_column('JobEmbeddings', 'EmbeddingType')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('JobEmbeddings', sa.Column('EmbeddingType', postgresql.ENUM('ALL', name='embeddingtype'), autoincrement=False, nullable=False))
    op.add_column('CVEmbeddings', sa.Column('EmbeddingType', postgresql.ENUM('ALL', name='embeddingtype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
