"""update tables

Revision ID: 7b7fe88d1273
Revises: 71079262d6bc
Create Date: 2026-04-02 05:57:51.325826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '7b7fe88d1273'
down_revision: Union[str, Sequence[str], None] = '71079262d6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
