"""add application models

Revision ID: ef942e427254
Revises: 43dda7c82982
Create Date: 2026-03-23 11:13:48.376162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ef942e427254'
down_revision: Union[str, Sequence[str], None] = '43dda7c82982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Applications',
    sa.Column('JobId', sa.Integer(), nullable=False),
    sa.Column('CVId', sa.Integer(), nullable=False),
    sa.Column('ApplicantId', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('APPLIED', 'SHORTLISTED', 'INTERVIEW', 'REJECTED', 'HIRED', name='applicationstatus'), nullable=False),
    sa.Column('CoverLetter', sa.Text(), nullable=True),
    sa.Column('AppliedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['ApplicantId'], ['users.Id'], ),
    sa.ForeignKeyConstraint(['CVId'], ['CVs.Id'], ),
    sa.ForeignKeyConstraint(['JobId'], ['Jobs.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('JobId', 'CVId', name='uq_job_cv')
    )
    op.create_table('ApplicationHistories',
    sa.Column('ApplicationId', sa.Integer(), nullable=False),
    sa.Column('Status', sa.Enum('APPLIED', 'SHORTLISTED', 'INTERVIEW', 'REJECTED', 'HIRED', name='applicationstatus'), nullable=False),
    sa.Column('Note', sa.String(length=1000), nullable=True),
    sa.Column('ChangedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ChangedById', sa.Integer(), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['ApplicationId'], ['Applications.Id'], ),
    sa.ForeignKeyConstraint(['ChangedById'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ApplicationHistories')
    op.drop_table('Applications')
    # ### end Alembic commands ###
