"""init

Revision ID: ff7e2711af63
Revises: 
Create Date: 2026-03-21 22:50:27.567609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ff7e2711af63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Jobs',
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('RequirementsText', sa.Text(), nullable=True),
    sa.Column('MinExperience', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('EducationLevel', sa.Enum('HIGH_SCHOOL', 'BACHELOR', 'MASTER', 'PHD', name='educationlevel'), nullable=True),
    sa.Column('Status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'DELETED', name='jobstatus'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('CVs',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('FileUrl', sa.String(length=500), nullable=False),
    sa.Column('FileType', sa.Enum('PDF', 'DOCX', 'TXT', name='cvfiletype'), nullable=True),
    sa.Column('RawText', sa.Text(), nullable=True),
    sa.Column('CleanText', sa.Text(), nullable=True),
    sa.Column('Summary', sa.Text(), nullable=True),
    sa.Column('Language', sa.String(length=20), server_default='en', nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('PositionId', sa.Integer(), nullable=True),
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['PositionId'], ['Jobs.Id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # 👇 tạo enum trước
    batch_status_enum = postgresql.ENUM(
        'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED',
        name='batchstatus'
    )
    batch_status_enum.create(op.get_bind())

    # 👇 sau đó mới add column
    op.add_column(
        'ScreeningBatches',
        sa.Column('Status', batch_status_enum, nullable=False)
    )
    op.create_foreign_key(None, 'CVEmbeddings', 'CVs', ['CVId'], ['Id'])
    op.create_foreign_key(None, 'CVSkills', 'CVs', ['CVId'], ['Id'])
    op.add_column('Educations', sa.Column('Level', sa.Enum('HIGH_SCHOOL', 'BACHELOR', 'MASTER', 'PHD', name='educationlevel'), nullable=True))
    op.create_foreign_key(None, 'Educations', 'CVs', ['CVId'], ['Id'])
    op.create_foreign_key(None, 'Experiences', 'CVs', ['CVId'], ['Id'])
    op.create_foreign_key(None, 'JobEmbeddings', 'Jobs', ['JobId'], ['Id'])
    op.create_foreign_key(None, 'JobSkills', 'Jobs', ['JobId'], ['Id'])
    op.create_foreign_key(None, 'MatchResults', 'Jobs', ['JobId'], ['Id'])
    op.create_foreign_key(None, 'MatchResults', 'CVs', ['CVId'], ['Id'])
    op.create_foreign_key(None, 'ScreeningBatches', 'Jobs', ['JobId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ScreeningBatches', type_='foreignkey')
    op.drop_column('ScreeningBatches', 'Status')
    op.drop_constraint(None, 'MatchResults', type_='foreignkey')
    op.drop_constraint(None, 'MatchResults', type_='foreignkey')
    op.drop_constraint(None, 'JobSkills', type_='foreignkey')
    op.drop_constraint(None, 'JobEmbeddings', type_='foreignkey')
    op.drop_column('JobEmbeddings', 'EmbeddingType')
    op.drop_constraint(None, 'Experiences', type_='foreignkey')
    op.drop_constraint(None, 'Educations', type_='foreignkey')
    op.drop_column('Educations', 'Level')
    op.drop_constraint(None, 'CVSkills', type_='foreignkey')
    op.drop_constraint(None, 'CVEmbeddings', type_='foreignkey')
    op.drop_column('CVEmbeddings', 'EmbeddingType')
    op.drop_table('CVs')
    op.drop_table('Jobs')
    # Drop enums
    batch_status_enum = postgresql.ENUM(
        'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED',
        name='batchstatus'
    )
    batch_status_enum.drop(op.get_bind())
    education_level_enum = sa.Enum('HIGH_SCHOOL', 'BACHELOR', 'MASTER', 'PHD', name='educationlevel')
    education_level_enum.drop(op.get_bind())
    job_status_enum = sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'DELETED', name='jobstatus')
    job_status_enum.drop(op.get_bind())
    cv_filetype_enum = sa.Enum('PDF', 'DOCX', 'TXT', name='cvfiletype')
    cv_filetype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
